name: Deploy Discord Bot

on:
  push:
    branches:
      - main  # or any branch you want
  schedule:
    - cron: '*/5 * * * *'  # Every minute (shortest possible cron interval in GitHub Actions)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py

      - name: Run Bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          SERVER: ${{ secrets.SERVER }}
          CHANNEL: ${{ secrets.CHANNEL }}
        run: python discordbot.py
