name: Deploy Discord Bot

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          SERVER: ${{ secrets.SERVER }}
          CHANNEL: ${{ secrets.CHANNEL }}
        run: python discordbot.py
